jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install @semantic-release/changelog -D
      - run: npm install @semantic-release/git -D
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npx semantic-release
"on":
  push:
    branches:
      - master
